### 
GET http://localhost:4000/api/rsa/pubKey

### 
GET http://localhost:4000/api/paillier/pubKey

###
POST http://localhost:4000/api/rsa/sign
content-type: application/json

{
    "message": "143353535"
}

###
POST http://localhost:4000/api/rsa/verify
content-type: application/json

{
    "message": "1434545"
}

###
POST http://localhost:4000/api/rsa/decrypt
content-type: application/json

{
    "message": "87687687687687"
}

###
POST http://localhost:4000/api/rsa/encrypt
content-type: application/json

{
    "message": "876876"
}

###
POST http://localhost:4000/api/paillier/decrypt
content-type: application/json

{
    "message": "110"
}

### DELETE http://localhost:3000/api/users/:id