### 
GET http://localhost:3000/api/rsa/pubKey

### 
GET http://localhost:3000/api/paillier/pubKey

###
POST http://localhost:3000/api/rsa/sign
content-type: application/json

{
    "message": "blindMessage"
}

###
POST http://localhost:3000/api/rsa/decrypt
content-type: application/json

{
    "message": "paquitomola"
}

###
POST http://localhost:3000/api/paillier/decrypt
content-type: application/json

{
    "message": "decryptingg"
}

### DELETE http://localhost:3000/api/users/:id